In [1]:
import os
print(os.listdir(r"C:\Users\cmebr\OneDrive\Documents\GitHub\110BProj1"))

['.git', '.gitignore', '.ipynb_checkpoints', 'A few attempts at Optimization.ipynb', 'Data loading, cleaning, etc..ipynb', 'project-1-sudoku-challenge.zip.REMOVED.git-id', 'README.md', 'README.txt']


In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [5]:
data = pd.read_csv(r"C:\Users\cmebr\Desktop\110BProj1\large1.csv")

In [6]:
data.head()

quizzes  \
0  0000000000000000085070100200000000000300060000...   
1  0000000000000000105000302000070000000030506204...   
2  0000000000000000246003080700000000000050200983...   
3  0000000000000000361028000000750400000000019400...   
4  0000000000000000700340900210030400000978000000...   

                                           solutions  
0  4267581939132645785873194268541327691329768456...  
1  9862154733246879155714392686573928418137546294...  
2  5794621831837956246243185794628397157156243983...  
3  4563178297894251361328964579752486138236719456...  
4  9782164531263549785347986212831457696978321454...

In [10]:
sudoku0 = data['quizzes'][0]
sol0 = data['solutions'][0]
print(np.reshape([int(c) for c in sudoku0], (9,9)))
print(np.reshape([int(c) for c in sol0], (9,9)))
print(np.reshape([int(c) for c in sol0], (1,9**2)))

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 8]
 [5 0 7 0 1 0 0 2 0]
 [0 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 6 0 0 0]
 [0 0 9 0 0 5 2 3 0]
 [0 6 0 0 0 3 0 1 0]
 [0 0 1 8 0 0 0 5 4]
 [0 4 0 6 9 0 0 0 7]]
[[4 2 6 7 5 8 1 9 3]
 [9 1 3 2 6 4 5 7 8]
 [5 8 7 3 1 9 4 2 6]
 [8 5 4 1 3 2 7 6 9]
 [1 3 2 9 7 6 8 4 5]
 [6 7 9 4 8 5 2 3 1]
 [7 6 8 5 4 3 9 1 2]
 [3 9 1 8 2 7 6 5 4]
 [2 4 5 6 9 1 3 8 7]]
[[4 2 6 7 5 8 1 9 3 9 1 3 2 6 4 5 7 8 5 8 7 3 1 9 4 2 6 8 5 4 1 3 2 7 6 9
  1 3 2 9 7 6 8 4 5 6 7 9 4 8 5 2 3 1 7 6 8 5 4 3 9 1 2 3 9 1 8 2 7 6 5 4
  2 4 5 6 9 1 3 8 7]]


That's about it really. Now for some implmentations.